// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class AuthRequest;
@class AuthRequestBuilder;
@class AuthResponse;
@class AuthResponseBuilder;
@class BasePush;
@class BasePushBuilder;
@class BaseRequest;
@class BaseRequestBuilder;
@class BaseResponse;
@class BaseResponseBuilder;
@class InitRequest;
@class InitRequestBuilder;
@class InitResponse;
@class InitResponseBuilder;
@class RecvDataPush;
@class RecvDataPushBuilder;
@class SendDataRequest;
@class SendDataRequestBuilder;
@class SendDataResponse;
@class SendDataResponseBuilder;
@class SwitchBackgroudPush;
@class SwitchBackgroudPushBuilder;
@class SwitchViewPush;
@class SwitchViewPushBuilder;


typedef NS_ENUM(SInt32, EmCmdId) {
  EmCmdIdEciNone = 0,
  EmCmdIdEciReqAuth = 10001,
  EmCmdIdEciReqSendData = 10002,
  EmCmdIdEciReqInit = 10003,
  EmCmdIdEciRespAuth = 20001,
  EmCmdIdEciRespSendData = 20002,
  EmCmdIdEciRespInit = 20003,
  EmCmdIdEciPushRecvData = 30001,
  EmCmdIdEciPushSwitchView = 30002,
  EmCmdIdEciPushSwitchBackgroud = 30003,
  EmCmdIdEciErrDecode = 29999,
};

BOOL EmCmdIdIsValidValue(EmCmdId value);
NSString *NSStringFromEmCmdId(EmCmdId value);

typedef NS_ENUM(SInt32, EmErrorCode) {
  EmErrorCodeEecSystem = -1,
  EmErrorCodeEecNeedAuth = -2,
  EmErrorCodeEecSessionTimeout = -3,
  EmErrorCodeEecDecode = -4,
  EmErrorCodeEecDeviceIsBlock = -5,
  EmErrorCodeEecServiceUnAvalibleInBackground = -6,
  EmErrorCodeEecDeviceProtoVersionNeedUpdate = -7,
  EmErrorCodeEecPhoneProtoVersionNeedUpdate = -8,
  EmErrorCodeEecMaxReqInQueue = -9,
  EmErrorCodeEecUserExitWxAccount = -10,
};

BOOL EmErrorCodeIsValidValue(EmErrorCode value);
NSString *NSStringFromEmErrorCode(EmErrorCode value);

typedef NS_ENUM(SInt32, EmAuthMethod) {
  EmAuthMethodEamMd5 = 1,
  EmAuthMethodEamMacNoEncrypt = 2,
};

BOOL EmAuthMethodIsValidValue(EmAuthMethod value);
NSString *NSStringFromEmAuthMethod(EmAuthMethod value);

typedef NS_ENUM(SInt32, EmInitRespFieldFilter) {
  EmInitRespFieldFilterEirffUserNickName = 1,
  EmInitRespFieldFilterEirffPlatformType = 2,
  EmInitRespFieldFilterEirffModel = 4,
  EmInitRespFieldFilterEirffOs = 8,
  EmInitRespFieldFilterEirffTime = 16,
  EmInitRespFieldFilterEirffTimeZone = 32,
  EmInitRespFieldFilterEirffTimeString = 64,
};

BOOL EmInitRespFieldFilterIsValidValue(EmInitRespFieldFilter value);
NSString *NSStringFromEmInitRespFieldFilter(EmInitRespFieldFilter value);

typedef NS_ENUM(SInt32, EmInitScence) {
  EmInitScenceEisDeviceChat = 1,
  EmInitScenceEisAutoSync = 2,
};

BOOL EmInitScenceIsValidValue(EmInitScence value);
NSString *NSStringFromEmInitScence(EmInitScence value);

typedef NS_ENUM(SInt32, EmPlatformType) {
  EmPlatformTypeEptIos = 1,
  EmPlatformTypeEptAndriod = 2,
  EmPlatformTypeEptWp = 3,
  EmPlatformTypeEptS60V3 = 4,
  EmPlatformTypeEptS60V5 = 5,
  EmPlatformTypeEptS40 = 6,
  EmPlatformTypeEptBb = 7,
};

BOOL EmPlatformTypeIsValidValue(EmPlatformType value);
NSString *NSStringFromEmPlatformType(EmPlatformType value);

typedef NS_ENUM(SInt32, EmDeviceDataType) {
  EmDeviceDataTypeEddtManufatureSvr = 0,
  EmDeviceDataTypeEddtWxWristBand = 1,
  EmDeviceDataTypeEddtWxDeviceHtmlChatView = 10001,
};

BOOL EmDeviceDataTypeIsValidValue(EmDeviceDataType value);
NSString *NSStringFromEmDeviceDataType(EmDeviceDataType value);

typedef NS_ENUM(SInt32, EmSwitchViewOp) {
  EmSwitchViewOpEsvoEnter = 1,
  EmSwitchViewOpEsvoExit = 2,
};

BOOL EmSwitchViewOpIsValidValue(EmSwitchViewOp value);
NSString *NSStringFromEmSwitchViewOp(EmSwitchViewOp value);

typedef NS_ENUM(SInt32, EmViewId) {
  EmViewIdEviDeviceChatView = 1,
  EmViewIdEviDeviceChatHtmlView = 2,
};

BOOL EmViewIdIsValidValue(EmViewId value);
NSString *NSStringFromEmViewId(EmViewId value);

typedef NS_ENUM(SInt32, EmSwitchBackgroundOp) {
  EmSwitchBackgroundOpEsboEnterBackground = 1,
  EmSwitchBackgroundOpEsboEnterForground = 2,
  EmSwitchBackgroundOpEsboSleep = 3,
};

BOOL EmSwitchBackgroundOpIsValidValue(EmSwitchBackgroundOp value);
NSString *NSStringFromEmSwitchBackgroundOp(EmSwitchBackgroundOp value);


@interface MmBpRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BaseRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BaseRequestBuilder*) builder;
+ (BaseRequestBuilder*) builder;
+ (BaseRequestBuilder*) builderWithPrototype:(BaseRequest*) prototype;
- (BaseRequestBuilder*) toBuilder;

+ (BaseRequest*) parseFromData:(NSData*) data;
+ (BaseRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseRequest*) parseFromInputStream:(NSInputStream*) input;
+ (BaseRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BaseRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BaseRequestBuilder : PBGeneratedMessageBuilder {
@private
  BaseRequest* resultBaseRequest;
}

- (BaseRequest*) defaultInstance;

- (BaseRequestBuilder*) clear;
- (BaseRequestBuilder*) clone;

- (BaseRequest*) build;
- (BaseRequest*) buildPartial;

- (BaseRequestBuilder*) mergeFrom:(BaseRequest*) other;
- (BaseRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BaseRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define BaseResponse_ErrCode @"errCode"
#define BaseResponse_ErrMsg @"errMsg"
@interface BaseResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasErrCode_:1;
  BOOL hasErrMsg_:1;
  SInt32 errCode;
  NSString* errMsg;
}
- (BOOL) hasErrCode;
- (BOOL) hasErrMsg;
@property (readonly) SInt32 errCode;
@property (readonly, strong) NSString* errMsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BaseResponseBuilder*) builder;
+ (BaseResponseBuilder*) builder;
+ (BaseResponseBuilder*) builderWithPrototype:(BaseResponse*) prototype;
- (BaseResponseBuilder*) toBuilder;

+ (BaseResponse*) parseFromData:(NSData*) data;
+ (BaseResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseResponse*) parseFromInputStream:(NSInputStream*) input;
+ (BaseResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BaseResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BaseResponseBuilder : PBGeneratedMessageBuilder {
@private
  BaseResponse* resultBaseResponse;
}

- (BaseResponse*) defaultInstance;

- (BaseResponseBuilder*) clear;
- (BaseResponseBuilder*) clone;

- (BaseResponse*) build;
- (BaseResponse*) buildPartial;

- (BaseResponseBuilder*) mergeFrom:(BaseResponse*) other;
- (BaseResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BaseResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrCode;
- (SInt32) errCode;
- (BaseResponseBuilder*) setErrCode:(SInt32) value;
- (BaseResponseBuilder*) clearErrCode;

- (BOOL) hasErrMsg;
- (NSString*) errMsg;
- (BaseResponseBuilder*) setErrMsg:(NSString*) value;
- (BaseResponseBuilder*) clearErrMsg;
@end

@interface BasePush : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BasePushBuilder*) builder;
+ (BasePushBuilder*) builder;
+ (BasePushBuilder*) builderWithPrototype:(BasePush*) prototype;
- (BasePushBuilder*) toBuilder;

+ (BasePush*) parseFromData:(NSData*) data;
+ (BasePush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasePush*) parseFromInputStream:(NSInputStream*) input;
+ (BasePush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BasePush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BasePush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BasePushBuilder : PBGeneratedMessageBuilder {
@private
  BasePush* resultBasePush;
}

- (BasePush*) defaultInstance;

- (BasePushBuilder*) clear;
- (BasePushBuilder*) clone;

- (BasePush*) build;
- (BasePush*) buildPartial;

- (BasePushBuilder*) mergeFrom:(BasePush*) other;
- (BasePushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BasePushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define AuthRequest_BaseRequest @"baseRequest"
#define AuthRequest_Md5DeviceTypeAndDeviceId @"md5DeviceTypeAndDeviceId"
#define AuthRequest_ProtoVersion @"protoVersion"
#define AuthRequest_AuthProto @"authProto"
#define AuthRequest_AuthMethod @"authMethod"
#define AuthRequest_AesSign @"aesSign"
#define AuthRequest_MacAddress @"macAddress"
#define AuthRequest_TimeZone @"timeZone"
#define AuthRequest_Language @"language"
#define AuthRequest_DeviceName @"deviceName"
@interface AuthRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasProtoVersion_:1;
  BOOL hasAuthProto_:1;
  BOOL hasTimeZone_:1;
  BOOL hasLanguage_:1;
  BOOL hasDeviceName_:1;
  BOOL hasBaseRequest_:1;
  BOOL hasMd5DeviceTypeAndDeviceId_:1;
  BOOL hasAesSign_:1;
  BOOL hasMacAddress_:1;
  BOOL hasAuthMethod_:1;
  SInt32 protoVersion;
  SInt32 authProto;
  NSString* timeZone;
  NSString* language;
  NSString* deviceName;
  BaseRequest* baseRequest;
  NSData* md5DeviceTypeAndDeviceId;
  NSData* aesSign;
  NSData* macAddress;
  EmAuthMethod authMethod;
}
- (BOOL) hasBaseRequest;
- (BOOL) hasMd5DeviceTypeAndDeviceId;
- (BOOL) hasProtoVersion;
- (BOOL) hasAuthProto;
- (BOOL) hasAuthMethod;
- (BOOL) hasAesSign;
- (BOOL) hasMacAddress;
- (BOOL) hasTimeZone;
- (BOOL) hasLanguage;
- (BOOL) hasDeviceName;
@property (readonly, strong) BaseRequest* baseRequest;
@property (readonly, strong) NSData* md5DeviceTypeAndDeviceId;
@property (readonly) SInt32 protoVersion;
@property (readonly) SInt32 authProto;
@property (readonly) EmAuthMethod authMethod;
@property (readonly, strong) NSData* aesSign;
@property (readonly, strong) NSData* macAddress;
@property (readonly, strong) NSString* timeZone;
@property (readonly, strong) NSString* language;
@property (readonly, strong) NSString* deviceName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthRequestBuilder*) builder;
+ (AuthRequestBuilder*) builder;
+ (AuthRequestBuilder*) builderWithPrototype:(AuthRequest*) prototype;
- (AuthRequestBuilder*) toBuilder;

+ (AuthRequest*) parseFromData:(NSData*) data;
+ (AuthRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthRequestBuilder : PBGeneratedMessageBuilder {
@private
  AuthRequest* resultAuthRequest;
}

- (AuthRequest*) defaultInstance;

- (AuthRequestBuilder*) clear;
- (AuthRequestBuilder*) clone;

- (AuthRequest*) build;
- (AuthRequest*) buildPartial;

- (AuthRequestBuilder*) mergeFrom:(AuthRequest*) other;
- (AuthRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseRequest;
- (BaseRequest*) baseRequest;
- (AuthRequestBuilder*) setBaseRequest:(BaseRequest*) value;
- (AuthRequestBuilder*) setBaseRequestBuilder:(BaseRequestBuilder*) builderForValue;
- (AuthRequestBuilder*) mergeBaseRequest:(BaseRequest*) value;
- (AuthRequestBuilder*) clearBaseRequest;

- (BOOL) hasMd5DeviceTypeAndDeviceId;
- (NSData*) md5DeviceTypeAndDeviceId;
- (AuthRequestBuilder*) setMd5DeviceTypeAndDeviceId:(NSData*) value;
- (AuthRequestBuilder*) clearMd5DeviceTypeAndDeviceId;

- (BOOL) hasProtoVersion;
- (SInt32) protoVersion;
- (AuthRequestBuilder*) setProtoVersion:(SInt32) value;
- (AuthRequestBuilder*) clearProtoVersion;

- (BOOL) hasAuthProto;
- (SInt32) authProto;
- (AuthRequestBuilder*) setAuthProto:(SInt32) value;
- (AuthRequestBuilder*) clearAuthProto;

- (BOOL) hasAuthMethod;
- (EmAuthMethod) authMethod;
- (AuthRequestBuilder*) setAuthMethod:(EmAuthMethod) value;
- (AuthRequestBuilder*) clearAuthMethod;

- (BOOL) hasAesSign;
- (NSData*) aesSign;
- (AuthRequestBuilder*) setAesSign:(NSData*) value;
- (AuthRequestBuilder*) clearAesSign;

- (BOOL) hasMacAddress;
- (NSData*) macAddress;
- (AuthRequestBuilder*) setMacAddress:(NSData*) value;
- (AuthRequestBuilder*) clearMacAddress;

- (BOOL) hasTimeZone;
- (NSString*) timeZone;
- (AuthRequestBuilder*) setTimeZone:(NSString*) value;
- (AuthRequestBuilder*) clearTimeZone;

- (BOOL) hasLanguage;
- (NSString*) language;
- (AuthRequestBuilder*) setLanguage:(NSString*) value;
- (AuthRequestBuilder*) clearLanguage;

- (BOOL) hasDeviceName;
- (NSString*) deviceName;
- (AuthRequestBuilder*) setDeviceName:(NSString*) value;
- (AuthRequestBuilder*) clearDeviceName;
@end

#define AuthResponse_BaseResponse @"baseResponse"
#define AuthResponse_AesSessionKey @"aesSessionKey"
@interface AuthResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBaseResponse_:1;
  BOOL hasAesSessionKey_:1;
  BaseResponse* baseResponse;
  NSData* aesSessionKey;
}
- (BOOL) hasBaseResponse;
- (BOOL) hasAesSessionKey;
@property (readonly, strong) BaseResponse* baseResponse;
@property (readonly, strong) NSData* aesSessionKey;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthResponseBuilder*) builder;
+ (AuthResponseBuilder*) builder;
+ (AuthResponseBuilder*) builderWithPrototype:(AuthResponse*) prototype;
- (AuthResponseBuilder*) toBuilder;

+ (AuthResponse*) parseFromData:(NSData*) data;
+ (AuthResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthResponseBuilder : PBGeneratedMessageBuilder {
@private
  AuthResponse* resultAuthResponse;
}

- (AuthResponse*) defaultInstance;

- (AuthResponseBuilder*) clear;
- (AuthResponseBuilder*) clone;

- (AuthResponse*) build;
- (AuthResponse*) buildPartial;

- (AuthResponseBuilder*) mergeFrom:(AuthResponse*) other;
- (AuthResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseResponse;
- (BaseResponse*) baseResponse;
- (AuthResponseBuilder*) setBaseResponse:(BaseResponse*) value;
- (AuthResponseBuilder*) setBaseResponseBuilder:(BaseResponseBuilder*) builderForValue;
- (AuthResponseBuilder*) mergeBaseResponse:(BaseResponse*) value;
- (AuthResponseBuilder*) clearBaseResponse;

- (BOOL) hasAesSessionKey;
- (NSData*) aesSessionKey;
- (AuthResponseBuilder*) setAesSessionKey:(NSData*) value;
- (AuthResponseBuilder*) clearAesSessionKey;
@end

#define InitRequest_BaseRequest @"baseRequest"
#define InitRequest_RespFieldFilter @"respFieldFilter"
#define InitRequest_Challenge @"challenge"
@interface InitRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBaseRequest_:1;
  BOOL hasRespFieldFilter_:1;
  BOOL hasChallenge_:1;
  BaseRequest* baseRequest;
  NSData* respFieldFilter;
  NSData* challenge;
}
- (BOOL) hasBaseRequest;
- (BOOL) hasRespFieldFilter;
- (BOOL) hasChallenge;
@property (readonly, strong) BaseRequest* baseRequest;
@property (readonly, strong) NSData* respFieldFilter;
@property (readonly, strong) NSData* challenge;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (InitRequestBuilder*) builder;
+ (InitRequestBuilder*) builder;
+ (InitRequestBuilder*) builderWithPrototype:(InitRequest*) prototype;
- (InitRequestBuilder*) toBuilder;

+ (InitRequest*) parseFromData:(NSData*) data;
+ (InitRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InitRequest*) parseFromInputStream:(NSInputStream*) input;
+ (InitRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InitRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (InitRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface InitRequestBuilder : PBGeneratedMessageBuilder {
@private
  InitRequest* resultInitRequest;
}

- (InitRequest*) defaultInstance;

- (InitRequestBuilder*) clear;
- (InitRequestBuilder*) clone;

- (InitRequest*) build;
- (InitRequest*) buildPartial;

- (InitRequestBuilder*) mergeFrom:(InitRequest*) other;
- (InitRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (InitRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseRequest;
- (BaseRequest*) baseRequest;
- (InitRequestBuilder*) setBaseRequest:(BaseRequest*) value;
- (InitRequestBuilder*) setBaseRequestBuilder:(BaseRequestBuilder*) builderForValue;
- (InitRequestBuilder*) mergeBaseRequest:(BaseRequest*) value;
- (InitRequestBuilder*) clearBaseRequest;

- (BOOL) hasRespFieldFilter;
- (NSData*) respFieldFilter;
- (InitRequestBuilder*) setRespFieldFilter:(NSData*) value;
- (InitRequestBuilder*) clearRespFieldFilter;

- (BOOL) hasChallenge;
- (NSData*) challenge;
- (InitRequestBuilder*) setChallenge:(NSData*) value;
- (InitRequestBuilder*) clearChallenge;
@end

#define InitResponse_BaseResponse @"baseResponse"
#define InitResponse_UserIdHigh @"userIdHigh"
#define InitResponse_UserIdLow @"userIdLow"
#define InitResponse_ChalleangeAnswer @"challeangeAnswer"
#define InitResponse_InitScence @"initScence"
#define InitResponse_AutoSyncMaxDurationSecond @"autoSyncMaxDurationSecond"
#define InitResponse_UserNickName @"userNickName"
#define InitResponse_PlatformType @"platformType"
#define InitResponse_Model @"model"
#define InitResponse_Os @"os"
#define InitResponse_Time @"time"
#define InitResponse_TimeZone @"timeZone"
#define InitResponse_TimeString @"timeString"
@interface InitResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTime_:1;
  BOOL hasTimeZone_:1;
  BOOL hasUserNickName_:1;
  BOOL hasModel_:1;
  BOOL hasOs_:1;
  BOOL hasTimeString_:1;
  BOOL hasBaseResponse_:1;
  BOOL hasUserIdHigh_:1;
  BOOL hasUserIdLow_:1;
  BOOL hasChalleangeAnswer_:1;
  BOOL hasAutoSyncMaxDurationSecond_:1;
  BOOL hasInitScence_:1;
  BOOL hasPlatformType_:1;
  SInt32 time;
  SInt32 timeZone;
  NSString* userNickName;
  NSString* model;
  NSString* os;
  NSString* timeString;
  BaseResponse* baseResponse;
  UInt32 userIdHigh;
  UInt32 userIdLow;
  UInt32 challeangeAnswer;
  UInt32 autoSyncMaxDurationSecond;
  EmInitScence initScence;
  EmPlatformType platformType;
}
- (BOOL) hasBaseResponse;
- (BOOL) hasUserIdHigh;
- (BOOL) hasUserIdLow;
- (BOOL) hasChalleangeAnswer;
- (BOOL) hasInitScence;
- (BOOL) hasAutoSyncMaxDurationSecond;
- (BOOL) hasUserNickName;
- (BOOL) hasPlatformType;
- (BOOL) hasModel;
- (BOOL) hasOs;
- (BOOL) hasTime;
- (BOOL) hasTimeZone;
- (BOOL) hasTimeString;
@property (readonly, strong) BaseResponse* baseResponse;
@property (readonly) UInt32 userIdHigh;
@property (readonly) UInt32 userIdLow;
@property (readonly) UInt32 challeangeAnswer;
@property (readonly) EmInitScence initScence;
@property (readonly) UInt32 autoSyncMaxDurationSecond;
@property (readonly, strong) NSString* userNickName;
@property (readonly) EmPlatformType platformType;
@property (readonly, strong) NSString* model;
@property (readonly, strong) NSString* os;
@property (readonly) SInt32 time;
@property (readonly) SInt32 timeZone;
@property (readonly, strong) NSString* timeString;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (InitResponseBuilder*) builder;
+ (InitResponseBuilder*) builder;
+ (InitResponseBuilder*) builderWithPrototype:(InitResponse*) prototype;
- (InitResponseBuilder*) toBuilder;

+ (InitResponse*) parseFromData:(NSData*) data;
+ (InitResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InitResponse*) parseFromInputStream:(NSInputStream*) input;
+ (InitResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (InitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface InitResponseBuilder : PBGeneratedMessageBuilder {
@private
  InitResponse* resultInitResponse;
}

- (InitResponse*) defaultInstance;

- (InitResponseBuilder*) clear;
- (InitResponseBuilder*) clone;

- (InitResponse*) build;
- (InitResponse*) buildPartial;

- (InitResponseBuilder*) mergeFrom:(InitResponse*) other;
- (InitResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (InitResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseResponse;
- (BaseResponse*) baseResponse;
- (InitResponseBuilder*) setBaseResponse:(BaseResponse*) value;
- (InitResponseBuilder*) setBaseResponseBuilder:(BaseResponseBuilder*) builderForValue;
- (InitResponseBuilder*) mergeBaseResponse:(BaseResponse*) value;
- (InitResponseBuilder*) clearBaseResponse;

- (BOOL) hasUserIdHigh;
- (UInt32) userIdHigh;
- (InitResponseBuilder*) setUserIdHigh:(UInt32) value;
- (InitResponseBuilder*) clearUserIdHigh;

- (BOOL) hasUserIdLow;
- (UInt32) userIdLow;
- (InitResponseBuilder*) setUserIdLow:(UInt32) value;
- (InitResponseBuilder*) clearUserIdLow;

- (BOOL) hasChalleangeAnswer;
- (UInt32) challeangeAnswer;
- (InitResponseBuilder*) setChalleangeAnswer:(UInt32) value;
- (InitResponseBuilder*) clearChalleangeAnswer;

- (BOOL) hasInitScence;
- (EmInitScence) initScence;
- (InitResponseBuilder*) setInitScence:(EmInitScence) value;
- (InitResponseBuilder*) clearInitScence;

- (BOOL) hasAutoSyncMaxDurationSecond;
- (UInt32) autoSyncMaxDurationSecond;
- (InitResponseBuilder*) setAutoSyncMaxDurationSecond:(UInt32) value;
- (InitResponseBuilder*) clearAutoSyncMaxDurationSecond;

- (BOOL) hasUserNickName;
- (NSString*) userNickName;
- (InitResponseBuilder*) setUserNickName:(NSString*) value;
- (InitResponseBuilder*) clearUserNickName;

- (BOOL) hasPlatformType;
- (EmPlatformType) platformType;
- (InitResponseBuilder*) setPlatformType:(EmPlatformType) value;
- (InitResponseBuilder*) clearPlatformType;

- (BOOL) hasModel;
- (NSString*) model;
- (InitResponseBuilder*) setModel:(NSString*) value;
- (InitResponseBuilder*) clearModel;

- (BOOL) hasOs;
- (NSString*) os;
- (InitResponseBuilder*) setOs:(NSString*) value;
- (InitResponseBuilder*) clearOs;

- (BOOL) hasTime;
- (SInt32) time;
- (InitResponseBuilder*) setTime:(SInt32) value;
- (InitResponseBuilder*) clearTime;

- (BOOL) hasTimeZone;
- (SInt32) timeZone;
- (InitResponseBuilder*) setTimeZone:(SInt32) value;
- (InitResponseBuilder*) clearTimeZone;

- (BOOL) hasTimeString;
- (NSString*) timeString;
- (InitResponseBuilder*) setTimeString:(NSString*) value;
- (InitResponseBuilder*) clearTimeString;
@end

#define SendDataRequest_BaseRequest @"baseRequest"
#define SendDataRequest_Datan @"datan"
#define SendDataRequest_Type @"type"
@interface SendDataRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBaseRequest_:1;
  BOOL hasDatan_:1;
  BOOL hasType_:1;
  BaseRequest* baseRequest;
  NSData* datan;
  EmDeviceDataType type;
}
- (BOOL) hasBaseRequest;
- (BOOL) hasDatan;
- (BOOL) hasType;
@property (readonly, strong) BaseRequest* baseRequest;
@property (readonly, strong) NSData* datan;
@property (readonly) EmDeviceDataType type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendDataRequestBuilder*) builder;
+ (SendDataRequestBuilder*) builder;
+ (SendDataRequestBuilder*) builderWithPrototype:(SendDataRequest*) prototype;
- (SendDataRequestBuilder*) toBuilder;

+ (SendDataRequest*) parseFromData:(NSData*) data;
+ (SendDataRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendDataRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SendDataRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendDataRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendDataRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendDataRequestBuilder : PBGeneratedMessageBuilder {
@private
  SendDataRequest* resultSendDataRequest;
}

- (SendDataRequest*) defaultInstance;

- (SendDataRequestBuilder*) clear;
- (SendDataRequestBuilder*) clone;

- (SendDataRequest*) build;
- (SendDataRequest*) buildPartial;

- (SendDataRequestBuilder*) mergeFrom:(SendDataRequest*) other;
- (SendDataRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendDataRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseRequest;
- (BaseRequest*) baseRequest;
- (SendDataRequestBuilder*) setBaseRequest:(BaseRequest*) value;
- (SendDataRequestBuilder*) setBaseRequestBuilder:(BaseRequestBuilder*) builderForValue;
- (SendDataRequestBuilder*) mergeBaseRequest:(BaseRequest*) value;
- (SendDataRequestBuilder*) clearBaseRequest;

- (BOOL) hasDatan;
- (NSData*) datan;
- (SendDataRequestBuilder*) setDatan:(NSData*) value;
- (SendDataRequestBuilder*) clearDatan;

- (BOOL) hasType;
- (EmDeviceDataType) type;
- (SendDataRequestBuilder*) setType:(EmDeviceDataType) value;
- (SendDataRequestBuilder*) clearType;
@end

#define SendDataResponse_BaseResponse @"baseResponse"
#define SendDataResponse_Datan @"datan"
@interface SendDataResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBaseResponse_:1;
  BOOL hasDatan_:1;
  BaseResponse* baseResponse;
  NSData* datan;
}
- (BOOL) hasBaseResponse;
- (BOOL) hasDatan;
@property (readonly, strong) BaseResponse* baseResponse;
@property (readonly, strong) NSData* datan;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendDataResponseBuilder*) builder;
+ (SendDataResponseBuilder*) builder;
+ (SendDataResponseBuilder*) builderWithPrototype:(SendDataResponse*) prototype;
- (SendDataResponseBuilder*) toBuilder;

+ (SendDataResponse*) parseFromData:(NSData*) data;
+ (SendDataResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendDataResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SendDataResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendDataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendDataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendDataResponseBuilder : PBGeneratedMessageBuilder {
@private
  SendDataResponse* resultSendDataResponse;
}

- (SendDataResponse*) defaultInstance;

- (SendDataResponseBuilder*) clear;
- (SendDataResponseBuilder*) clone;

- (SendDataResponse*) build;
- (SendDataResponse*) buildPartial;

- (SendDataResponseBuilder*) mergeFrom:(SendDataResponse*) other;
- (SendDataResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendDataResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBaseResponse;
- (BaseResponse*) baseResponse;
- (SendDataResponseBuilder*) setBaseResponse:(BaseResponse*) value;
- (SendDataResponseBuilder*) setBaseResponseBuilder:(BaseResponseBuilder*) builderForValue;
- (SendDataResponseBuilder*) mergeBaseResponse:(BaseResponse*) value;
- (SendDataResponseBuilder*) clearBaseResponse;

- (BOOL) hasDatan;
- (NSData*) datan;
- (SendDataResponseBuilder*) setDatan:(NSData*) value;
- (SendDataResponseBuilder*) clearDatan;
@end

#define RecvDataPush_BasePush @"basePush"
#define RecvDataPush_Datan @"datan"
#define RecvDataPush_Type @"type"
@interface RecvDataPush : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBasePush_:1;
  BOOL hasDatan_:1;
  BOOL hasType_:1;
  BasePush* basePush;
  NSData* datan;
  EmDeviceDataType type;
}
- (BOOL) hasBasePush;
- (BOOL) hasDatan;
- (BOOL) hasType;
@property (readonly, strong) BasePush* basePush;
@property (readonly, strong) NSData* datan;
@property (readonly) EmDeviceDataType type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RecvDataPushBuilder*) builder;
+ (RecvDataPushBuilder*) builder;
+ (RecvDataPushBuilder*) builderWithPrototype:(RecvDataPush*) prototype;
- (RecvDataPushBuilder*) toBuilder;

+ (RecvDataPush*) parseFromData:(NSData*) data;
+ (RecvDataPush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RecvDataPush*) parseFromInputStream:(NSInputStream*) input;
+ (RecvDataPush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RecvDataPush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RecvDataPush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RecvDataPushBuilder : PBGeneratedMessageBuilder {
@private
  RecvDataPush* resultRecvDataPush;
}

- (RecvDataPush*) defaultInstance;

- (RecvDataPushBuilder*) clear;
- (RecvDataPushBuilder*) clone;

- (RecvDataPush*) build;
- (RecvDataPush*) buildPartial;

- (RecvDataPushBuilder*) mergeFrom:(RecvDataPush*) other;
- (RecvDataPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RecvDataPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasePush;
- (BasePush*) basePush;
- (RecvDataPushBuilder*) setBasePush:(BasePush*) value;
- (RecvDataPushBuilder*) setBasePushBuilder:(BasePushBuilder*) builderForValue;
- (RecvDataPushBuilder*) mergeBasePush:(BasePush*) value;
- (RecvDataPushBuilder*) clearBasePush;

- (BOOL) hasDatan;
- (NSData*) datan;
- (RecvDataPushBuilder*) setDatan:(NSData*) value;
- (RecvDataPushBuilder*) clearDatan;

- (BOOL) hasType;
- (EmDeviceDataType) type;
- (RecvDataPushBuilder*) setType:(EmDeviceDataType) value;
- (RecvDataPushBuilder*) clearType;
@end

#define SwitchViewPush_BasePush @"basePush"
#define SwitchViewPush_SwitchViewOp @"switchViewOp"
#define SwitchViewPush_ViewId @"viewId"
@interface SwitchViewPush : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBasePush_:1;
  BOOL hasSwitchViewOp_:1;
  BOOL hasViewId_:1;
  BasePush* basePush;
  EmSwitchViewOp switchViewOp;
  EmViewId viewId;
}
- (BOOL) hasBasePush;
- (BOOL) hasSwitchViewOp;
- (BOOL) hasViewId;
@property (readonly, strong) BasePush* basePush;
@property (readonly) EmSwitchViewOp switchViewOp;
@property (readonly) EmViewId viewId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwitchViewPushBuilder*) builder;
+ (SwitchViewPushBuilder*) builder;
+ (SwitchViewPushBuilder*) builderWithPrototype:(SwitchViewPush*) prototype;
- (SwitchViewPushBuilder*) toBuilder;

+ (SwitchViewPush*) parseFromData:(NSData*) data;
+ (SwitchViewPush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchViewPush*) parseFromInputStream:(NSInputStream*) input;
+ (SwitchViewPush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchViewPush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwitchViewPush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwitchViewPushBuilder : PBGeneratedMessageBuilder {
@private
  SwitchViewPush* resultSwitchViewPush;
}

- (SwitchViewPush*) defaultInstance;

- (SwitchViewPushBuilder*) clear;
- (SwitchViewPushBuilder*) clone;

- (SwitchViewPush*) build;
- (SwitchViewPush*) buildPartial;

- (SwitchViewPushBuilder*) mergeFrom:(SwitchViewPush*) other;
- (SwitchViewPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwitchViewPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasePush;
- (BasePush*) basePush;
- (SwitchViewPushBuilder*) setBasePush:(BasePush*) value;
- (SwitchViewPushBuilder*) setBasePushBuilder:(BasePushBuilder*) builderForValue;
- (SwitchViewPushBuilder*) mergeBasePush:(BasePush*) value;
- (SwitchViewPushBuilder*) clearBasePush;

- (BOOL) hasSwitchViewOp;
- (EmSwitchViewOp) switchViewOp;
- (SwitchViewPushBuilder*) setSwitchViewOp:(EmSwitchViewOp) value;
- (SwitchViewPushBuilder*) clearSwitchViewOp;

- (BOOL) hasViewId;
- (EmViewId) viewId;
- (SwitchViewPushBuilder*) setViewId:(EmViewId) value;
- (SwitchViewPushBuilder*) clearViewId;
@end

#define SwitchBackgroudPush_BasePush @"basePush"
#define SwitchBackgroudPush_SwitchBackgroundOp @"switchBackgroundOp"
@interface SwitchBackgroudPush : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBasePush_:1;
  BOOL hasSwitchBackgroundOp_:1;
  BasePush* basePush;
  EmSwitchBackgroundOp switchBackgroundOp;
}
- (BOOL) hasBasePush;
- (BOOL) hasSwitchBackgroundOp;
@property (readonly, strong) BasePush* basePush;
@property (readonly) EmSwitchBackgroundOp switchBackgroundOp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SwitchBackgroudPushBuilder*) builder;
+ (SwitchBackgroudPushBuilder*) builder;
+ (SwitchBackgroudPushBuilder*) builderWithPrototype:(SwitchBackgroudPush*) prototype;
- (SwitchBackgroudPushBuilder*) toBuilder;

+ (SwitchBackgroudPush*) parseFromData:(NSData*) data;
+ (SwitchBackgroudPush*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchBackgroudPush*) parseFromInputStream:(NSInputStream*) input;
+ (SwitchBackgroudPush*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SwitchBackgroudPush*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SwitchBackgroudPush*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SwitchBackgroudPushBuilder : PBGeneratedMessageBuilder {
@private
  SwitchBackgroudPush* resultSwitchBackgroudPush;
}

- (SwitchBackgroudPush*) defaultInstance;

- (SwitchBackgroudPushBuilder*) clear;
- (SwitchBackgroudPushBuilder*) clone;

- (SwitchBackgroudPush*) build;
- (SwitchBackgroudPush*) buildPartial;

- (SwitchBackgroudPushBuilder*) mergeFrom:(SwitchBackgroudPush*) other;
- (SwitchBackgroudPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SwitchBackgroudPushBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBasePush;
- (BasePush*) basePush;
- (SwitchBackgroudPushBuilder*) setBasePush:(BasePush*) value;
- (SwitchBackgroudPushBuilder*) setBasePushBuilder:(BasePushBuilder*) builderForValue;
- (SwitchBackgroudPushBuilder*) mergeBasePush:(BasePush*) value;
- (SwitchBackgroudPushBuilder*) clearBasePush;

- (BOOL) hasSwitchBackgroundOp;
- (EmSwitchBackgroundOp) switchBackgroundOp;
- (SwitchBackgroudPushBuilder*) setSwitchBackgroundOp:(EmSwitchBackgroundOp) value;
- (SwitchBackgroudPushBuilder*) clearSwitchBackgroundOp;
@end


// @@protoc_insertion_point(global_scope)
